package net.idik.lib.cipher.so.task

import net.idik.lib.cipher.so.extension.KeyExt

class CipherSoHeaderBuilder {
    private List<KeyExt> keys

    private String fileName

    CipherSoHeaderBuilder(String fileName, List<KeyExt> keys) {
        this.fileName = fileName
        this.keys = keys
    }

    List<String> build() {
        List<String> lines = new ArrayList<>()
        lines.add("// Auto-Generated By Cipher.so - 林帅斌(me@idik.net)\n\n")
        lines.add("#ifndef CIPHER_${fileName.replaceAll("\\.", "_").toUpperCase(Locale.US)}\n")
        lines.add("#defind CIPHER_${fileName.replaceAll("\\.", "_").toUpperCase(Locale.US)}\n\n")
        keys.each {
            lines.add("const char* KEY_${it.name} = \"${it.value}\";\n")
        }
        lines.add("\n")
        lines.add("#endif //CIPHER_${fileName.replaceAll("\\.", "_").toUpperCase(Locale.US)}\n")
        lines
    }


}