package net.idik.lib.cipher.so.task

import net.idik.lib.cipher.so.extension.KeyExt

class SoHeaderBuilder {

    List<KeyExt> keys

    String fileName

    SoHeaderBuilder(String fileName, List<KeyExt> keys) {
        this.fileName = fileName
        this.keys = keys
    }

    List<String> build() {
        List<String> lines = new ArrayList<>()
        lines.add("// Auto-Generated By Cipher.so - 林帅斌 me@idik.net\n\n")
        lines.add("#ifndef CIPHER_EXTENSION_KEY_${fileName.replaceAll("\\.","_").toUpperCase(Locale.US)}\n")
        lines.add("#defind CIPHER_EXTENSION_KEY_${fileName.replaceAll("\\.","_").toUpperCase(Locale.US)}\n")
        keys.each {
            lines.add("const char* KEY_${it.name} = \"${it.value}\";\n")
        }
        lines.add("\n")
        lines.add("#endif //CIPHER_EXTENSION_KEY_${fileName.replaceAll("\\.","_").toUpperCase(Locale.US)}\n")
        lines
    }


}